server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/repair_system_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Europe/Paris&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB

  logging:
    level:
      root: INFO
      org.springframework.web: INFO
      org.hibernate.SQL: DEBUG

app:
  storage:
    upload-dir: ./uploads
    public-base-url: /media

jwt:
  secret: "0123456789876543210_!@%*()_HS512_long_secret_key_should_be_at_least_256_bits"
  access-token-expire-time: 7200000 # 2 heures
